Fixed missing file issue with homestead-prov
Metaswitch/clearwater-docker pull request #89
Opened 2018-05-14 06:00 UTC by mlda065

There was a bug in homestead-prov. [Here is my mailing list email](http://lists.projectclearwater.org/pipermail/clearwater_lists.projectclearwater.org/2018-May/003935.html) about it. I think it's also what is described in #70 .

The issue was that when homestead-prov spins up, it tries to find two files which aren't there.

* `/usr/share/clearwater/bin/clearwater-socket-factory-mgmt-wrapper`
* `/usr/share/clearwater/bin/clearwater-socket-factory-sig-wrapper`

This bug was introduced when homestead-prov was split off from homestead. The solution is to do `apt-get install homestead` when building the `homestead-prov` pod.

I still can't get homestead and homestead-prov to spin up. There's still some other issue. But this patch helps fix the first issue.

2018-05-14 12:32 UTC, richardwhiuk requested changes
I don't think this is the right fix.

If we just want `/usr/share/clearwater/bin/clearwater-socket-factory-mgmt-wrapper`, then that's provided by `clearwater-socket-factory`. 

I think the fix is just to have `homestead-prov` depend on `clearwater-socket-factory` (at https://github.com/Metaswitch/crest/blob/dev/debian/control#L30 ). As a workaround, you should just be able to add `clearwater-socket-factory` to the Dockerfile.

@mlda065 Does just adding `clearwater-socket-factory` to the Dockerfile fix the problem?

2018-05-14 23:41 UTC, mlda065 commented
Yep that fix works too.

What's the easiest way to modify a pull request? Or should I just submit a new pull request?

2018-05-16 17:45 UTC, johadalin commented
You can just push the latest version of your branch with the updated changes, and that should appear on here. If it's easier for you though you can also just close this PR and raise a new one.
Cheers 😃

2018-05-21 05:13 UTC, mlda065 commented
@richardwhiuk  I've changed it to `clearwater-socket-factory`. 

I'm not sure how I'm supposed to resolve your change request in github. I've done what you asked but github doesn't know it. It seems like your change request was to undo my change completely? I'm not familiar with this change request functionality in github.

2018-06-04 16:06 UTC, johadalin commented
@richardwhiuk @mlda065 what's the state of this PR?  
In testing on my set up, i haven't seen this crop up at all. I know you were seeing some other issues on your rig, so was this potentially just a misleading symptom, and not actually a core problem?  
Would be nice to get to the bottom of it either way

2018-06-27 03:27 UTC, mdavis-xyz commented
What happens when you run `k logs homestead-prov-xxx` on a functional deployment? Do you see the warnings about `clearwater-socket-factory-mgmt-wrapper` missing?

2018-06-27 08:24 UTC, johadalin commented
Hey @mlda065 
Yeah, i see those warnings on my setup. The logs don't look that great, but here's what i see on mine, and this is fully working:
```
09:22:30 cw-k8s-1 ~ $ kubectl logs homestead-prov-2511446158-l7xxz
2018-06-04 16:40:36,490 CRIT Supervisor running as root (no user in config file)
2018-06-04 16:40:36,490 WARN Included extra file "/etc/supervisor/conf.d/socket-factory.supervisord.conf" during parsing
2018-06-04 16:40:36,490 WARN Included extra file "/etc/supervisor/conf.d/clearwater-group.conf" during parsing
2018-06-04 16:40:36,490 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2018-06-04 16:40:36,490 WARN Included extra file "/etc/supervisor/conf.d/homestead-prov.conf" during parsing
2018-06-04 16:40:36,491 WARN Included extra file "/etc/supervisor/conf.d/snmpd.conf" during parsing
2018-06-04 16:40:36,491 WARN Included extra file "/etc/supervisor/conf.d/clearwater-infrastructure.conf" during parsing
2018-06-04 16:40:36,491 WARN Included extra file "/etc/supervisor/conf.d/supervisord.conf" during parsing
2018-06-04 16:40:36,510 INFO RPC interface 'supervisor' initialized
2018-06-04 16:40:36,510 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-06-04 16:40:36,510 INFO supervisord started with pid 1
2018-06-04 16:40:37,513 INFO spawned: 'snmpd' with pid 9
2018-06-04 16:40:37,513 INFO spawnerr: can't find command '/usr/share/clearwater/bin/clearwater-socket-factory-sig-wrapper'
2018-06-04 16:40:37,514 INFO spawned: 'clearwater-infrastructure' with pid 10
2018-06-04 16:40:37,515 INFO spawnerr: can't find command '/usr/share/clearwater/bin/clearwater-socket-factory-mgmt-wrapper'
2018-06-04 16:40:37,518 INFO success: snmpd entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-06-04 16:40:37,518 INFO success: clearwater-infrastructure entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2018-06-04 16:40:37,546 INFO exited: snmpd (exit status 0; expected)
2018-06-04 16:40:37,549 CRIT reaped unknown pid 29)
2018-06-04 16:40:38,581 INFO spawnerr: can't find command '/usr/share/clearwater/bin/clearwater-socket-factory-sig-wrapper'
2018-06-04 16:40:38,581 INFO spawnerr: can't find command '/usr/share/clearwater/bin/clearwater-socket-factory-mgmt-wrapper'
2018-06-04 16:40:39,591 CRIT reaped unknown pid 55)
2018-06-04 16:40:39,592 CRIT reaped unknown pid 54)
2018-06-04 16:40:40,593 INFO spawnerr: can't find command '/usr/share/clearwater/bin/clearwater-socket-factory-sig-wrapper'
2018-06-04 16:40:40,593 INFO spawnerr: can't find command '/usr/share/clearwater/bin/clearwater-socket-factory-mgmt-wrapper'
2018-06-04 16:40:40,784 CRIT reaped unknown pid 186)
2018-06-04 16:40:40,785 CRIT reaped unknown pid 185)
2018-06-04 16:40:40,805 CRIT reaped unknown pid 211)
2018-06-04 16:40:42,027 INFO spawned: 'homestead-prov' with pid 245
2018-06-04 16:40:42,028 INFO spawned: 'nginx' with pid 246
2018-06-04 16:40:43,232 INFO success: homestead-prov entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-04 16:40:43,232 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-06-04 16:40:44,233 INFO spawnerr: can't find command '/usr/share/clearwater/bin/clearwater-socket-factory-sig-wrapper'
2018-06-04 16:40:44,233 INFO gave up: socket-factory-sig entered FATAL state, too many start retries too quickly
2018-06-04 16:40:44,233 INFO spawnerr: can't find command '/usr/share/clearwater/bin/clearwater-socket-factory-mgmt-wrapper'
2018-06-04 16:40:44,233 INFO gave up: socket-factory-mgmt entered FATAL state, too many start retries too quickly
2018-06-04 16:40:44,240 INFO exited: clearwater-infrastructure (exit status 0; expected)
```

2018-08-14 04:44 UTC, mlda065 commented
It turns out that this dependency issue was not the cause of my problems. It was a red herring.

So you can either:

* Close this pull request without merging: the misleading warnings will remain
* Merge this request anyway: the misleading warnings will go away, but the image size will get even bigger

I'll leave that decision up to you.

2018-08-14 08:57 UTC, johadalin commented
@mlda065 Thanks for the update. I'll assign this to me for now, and try to have a think about what we want to do here soon, though it may not be for a few days or so at the moment 👍

2018-10-23 09:46 UTC, johadalin commented
Think we're going to close this down for now

2018-10-23 09:46 UTC, closed without merging